# Generated by Django 6.0.4 on 2026-08-24 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_progresslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learning_band',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='starting_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.CharField(choices=[('sequencing', 'Sequencing & Logic'), ('patterns', 'Pattern Recognition'), ('loops', 'Loop Optimization'), ('debugging', 'Debugging & Reasoning'), ('conditions', 'Conditional Logic')], max_length=50)),
                ('status', models.CharField(choices=[('INTRODUCED', 'Introduced'), ('DEVELOPING', 'Developing'), ('PROFICIENT', 'Proficient'), ('MASTERED', 'Mastered')], default='INTRODUCED', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'competency')},
            },
        ),
    ]
