# Generated by Django 6.0.4 on 2026-09-17 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_learning_band_userprofile_starting_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('instructions_markdown', models.TextField()),
                ('starter_html', models.TextField(blank=True, default='')),
                ('starter_css', models.TextField(blank=True, default='')),
                ('solution_criteria', models.JSONField(default=dict)),
                ('reward_xp', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_html', models.TextField(blank=True, null=True)),
                ('saved_css', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_challenge_progresses', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='api.webchallenge')),
            ],
            options={
                'unique_together': {('student', 'challenge')},
            },
        ),
    ]
