# Generated by Django 6.0.4 on 2026-09-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_webchallenge_studentchallengeprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webchallenge',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
